### ISSUE TITLE
trained weights and testing

### ISSUE THREAD

**Issue by ak9250** [grey-eye/talking-heads#1]
can you share your trained weights and how to test it

**Comment by MrCaracara** [comment]
Hey, @ak9250.

I don't have a proper set of trained weights yet, as I'm still changing the structure of the NN's quite often, and I haven't allowed the network to train for long enough. Otherwise, I would've uploaded it already. If you manage to train the network yourself, though, feel free to share your weights with the community!

**Comment by afung-git** [comment]
@MrCaracara ,

Any updates on sharing your trained weights? I would like to play around with the this and try to take a stab in writing the FT portion of it.
