### ISSUE TITLE
Question about the dataset normalization

### ISSUE THREAD

**Issue by subrtade662** [grey-eye/talking-heads#14]
Could you, please, explain the normalization in dataset initialization?
transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
In what range are the images after this operation?
I don't have the VoxCeleb2 dataset... 
I think the range should be [-1,1] since the generated images are also in this range ( the last layer of the generator is tanh ). 
Could it help the discriminator to distinguish between the two classes?
Thanks in advance

**Comment by BaldrLector** [comment]
hi @subrtade662 , i think use transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]) is beacuase VGG_19 and VGG_Face pretrained model used in this paper. Two model both use this Normalize

i don't know use tanh at last output, but since Totensor used in transformer, only range [0,1] part have information.
